"""Marketing agent data models.

Pydantic models for content decisions, generated content, and marketing cycle reports.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field


class Platform(str, Enum):
    """Social media platforms supported by the marketing agent."""

    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    THREADS = "threads"
    YOUTUBE = "youtube"


class ContentType(str, Enum):
    """Types of content the marketing agent can create."""

    TUTORIAL = "tutorial"
    DEMO = "demo"
    TIPS = "tips"
    THREAD = "thread"
    CASE_STUDY = "case_study"
    CAROUSEL = "carousel"
    VIDEO_REEL = "video_reel"
    ANNOUNCEMENT = "announcement"
    EDUCATIONAL = "educational"


class ContentDecision(BaseModel):
    """A strategic decision about what content to create.

    The reason stage outputs a list of these decisions.
    Each decision specifies: what to create, for which product, on which platform, and why.
    """

    product: str = Field(description="Product to promote (pilaster | genpeli | invoz)")
    platform: Platform = Field(description="Target social media platform")
    content_type: ContentType = Field(description="Type of content to create")
    topic: str = Field(description="What the content is about")
    reasoning: str = Field(description="Why this content, why now")
    priority: int = Field(default=1, ge=1, le=3, description="Priority (1=highest, 3=lowest)")
    estimated_engagement: str = Field(
        default="medium",
        pattern="^(low|medium|high)$",
        description="Expected engagement level",
    )


class GeneratedPiece(BaseModel):
    """A content piece generated by the marketing agent.

    Represents the output of the act stage: content created and ready for review/publishing.
    """

    piece_id: str = Field(description="Unique identifier for this content piece")
    decision: ContentDecision = Field(description="The decision that led to this content")
    text: str = Field(description="The generated text content")
    platform: Platform = Field(description="Target platform (duplicated for convenience)")
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When this content was generated",
    )
    model_used: str = Field(description="Claude model used for generation (e.g., sonnet-4-6)")
    status: str = Field(
        default="pending_review",
        pattern="^(pending_review|approved|published|rejected)$",
        description="Content lifecycle status",
    )
    post_url: str | None = Field(default=None, description="URL after publishing (if published)")


class MarketingCycleReport(BaseModel):
    """Summary of a complete marketing cycle run.

    Generated at the end of the evaluate stage for observability and cost tracking.
    """

    cycle_id: str = Field(description="Unique identifier for this cycle")
    started_at: datetime = Field(description="When the cycle started")
    completed_at: datetime = Field(description="When the cycle completed")
    decisions_made: int = Field(ge=0, description="Number of content decisions")
    pieces_generated: int = Field(ge=0, description="Number of content pieces generated")
    pieces_published: int = Field(ge=0, description="Number of pieces actually published")
    products_covered: list[str] = Field(
        default_factory=list, description="Products promoted in this cycle"
    )
    platforms_used: list[Platform] = Field(
        default_factory=list, description="Platforms targeted in this cycle"
    )
    total_cost_usd: float = Field(
        default=0.0, ge=0.0, description="Total API cost for this cycle"
    )
