"""Marketing agent data models.

Pydantic models for content decisions, generated content, marketing cycle reports,
and brand identity configuration.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class Platform(StrEnum):
    """Social media platforms supported by the marketing agent."""

    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    THREADS = "threads"
    YOUTUBE = "youtube"


class ContentType(StrEnum):
    """Types of content the marketing agent can create."""

    TUTORIAL = "tutorial"
    DEMO = "demo"
    TIPS = "tips"
    THREAD = "thread"
    CASE_STUDY = "case_study"
    CAROUSEL = "carousel"
    VIDEO_REEL = "video_reel"
    ANNOUNCEMENT = "announcement"
    EDUCATIONAL = "educational"


class ContentDecision(BaseModel):
    """A strategic decision about what content to create.

    The reason stage outputs these decisions.  Each specifies what to create,
    for which product (used as proof, not pitch), on which platform, and why.
    New authority-engine fields (content_pillar, hook, framework, repurpose_notes)
    have defaults so existing fallback decisions keep working.
    """

    product: str = Field(description="Product used as proof (pilaster | genpeli | invoz | none)")
    platform: Platform = Field(
        default=Platform.LINKEDIN, description="Target social media platform"
    )
    content_type: ContentType = Field(description="Type of content to create")
    content_pillar: str = Field(
        default="builder_stories",
        description="Authority pillar: builder_stories, ai_frameworks, industry_analysis, results_proof, contrarian_takes",
    )
    topic: str = Field(description="What the content is about")
    hook: str = Field(default="", description="Opening line of the post")
    framework: str = Field(default="original", description="Viral/content framework used")
    reasoning: str = Field(description="Why this content, why now")
    priority: int = Field(default=1, ge=1, le=3, description="Priority (1=highest, 3=lowest)")
    estimated_engagement: str = Field(
        default="medium",
        pattern="^(low|medium|high)$",
        description="Expected engagement level",
    )
    repurpose_notes: str = Field(default="", description="Adaptation notes for repurposing")


class GeneratedPiece(BaseModel):
    """A content piece generated by the marketing agent.

    Represents the output of the act stage: content created and ready for review/publishing.
    """

    piece_id: str = Field(description="Unique identifier for this content piece")
    decision: ContentDecision = Field(description="The decision that led to this content")
    text: str = Field(description="The generated text content")
    platform: Platform = Field(description="Target platform (duplicated for convenience)")
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When this content was generated",
    )
    model_used: str = Field(description="Claude model used for generation (e.g., sonnet-4-6)")
    status: str = Field(
        default="pending_review",
        pattern="^(pending_review|approved|published|rejected)$",
        description="Content lifecycle status",
    )
    post_url: str | None = Field(default=None, description="URL after publishing (if published)")


# ---------------------------------------------------------------------------
# Brand Identity models (loaded from config/brand.yaml)
# ---------------------------------------------------------------------------


class BrandVoice(BaseModel):
    """Voice configuration from brand.yaml."""

    archetype: str = ""
    summary: str = ""
    tone: list[str] = Field(default_factory=list)
    hooks: dict[str, str] = Field(default_factory=dict)
    closers: dict[str, str] = Field(default_factory=dict)
    language: dict[str, str] = Field(default_factory=dict)


class BrandPositioning(BaseModel):
    """Positioning from brand.yaml."""

    one_liner: str = ""
    category: str = ""
    differentiation: list[str] = Field(default_factory=list)
    what_i_am: list[str] = Field(default_factory=list)
    what_i_am_not: list[str] = Field(default_factory=list)
    market: str = ""


class ContentPillar(BaseModel):
    """Content pillar from brand.yaml."""

    id: str
    name: str
    description: str
    frequency: str = ""
    products: list[str] = Field(default_factory=list)
    goal: str = ""


class BrandIdentity(BaseModel):
    """Full brand identity loaded from config/brand.yaml.

    Graceful defaults for all fields so the agent works even with
    a partially filled brand.yaml or a missing file.
    Extra fields from YAML are ignored so the schema can evolve.
    """

    model_config = {"extra": "ignore"}

    story: dict[str, Any] = Field(default_factory=dict)
    positioning: BrandPositioning = Field(default_factory=BrandPositioning)
    offer: dict[str, Any] = Field(default_factory=dict)
    target_client: dict[str, Any] = Field(default_factory=dict)
    products_as_proof: dict[str, Any] = Field(default_factory=dict)
    voice: BrandVoice = Field(default_factory=BrandVoice)
    anti_patterns: dict[str, list[str]] = Field(default_factory=dict)
    competitor_accounts: dict[str, Any] = Field(default_factory=dict)
    content_pillars: list[ContentPillar] = Field(default_factory=list)
    platform_strategy: dict[str, Any] = Field(default_factory=dict)


class NicheInsight(BaseModel):
    """A single insight extracted from niche research."""

    source_url: str = ""
    source_title: str = ""
    category: str = Field(
        default="trending_topic",
        description="competitor_content | trending_topic | viral_pattern | industry_news",
    )
    hook: str | None = None
    topic: str = ""
    format: str = Field(default="text", description="text | carousel | video | document | image")
    engagement_signals: str = ""
    why_it_works: str = ""
    relevance_to_camilo: str = ""
    pillar_fit: list[str] = Field(default_factory=list)
    extracted_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())


class NicheResearchResult(BaseModel):
    """Complete niche research output for one cycle."""

    queries_run: list[str] = Field(default_factory=list)
    insights: list[NicheInsight] = Field(default_factory=list)
    trending_topics: list[str] = Field(default_factory=list)
    recommended_angles: list[str] = Field(default_factory=list)
    research_duration_ms: int = 0


class MarketingCycleReport(BaseModel):
    """Summary of a complete marketing cycle run.

    Generated at the end of the evaluate stage for observability and cost tracking.
    """

    cycle_id: str = Field(description="Unique identifier for this cycle")
    started_at: datetime = Field(description="When the cycle started")
    completed_at: datetime = Field(description="When the cycle completed")
    decisions_made: int = Field(ge=0, description="Number of content decisions")
    pieces_generated: int = Field(ge=0, description="Number of content pieces generated")
    pieces_published: int = Field(ge=0, description="Number of pieces actually published")
    products_covered: list[str] = Field(
        default_factory=list, description="Products promoted in this cycle"
    )
    platforms_used: list[Platform] = Field(
        default_factory=list, description="Platforms targeted in this cycle"
    )
    total_cost_usd: float = Field(default=0.0, ge=0.0, description="Total API cost for this cycle")
