name: Bug report
description: Report something broken
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What broke?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact sequence to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
